version: "3.8"

services:
    kommunicator:
        build: .
        env_file:
            - .env
        ports:
            - "8080:8080"
        networks:
            - docker_network
        depends_on:
            - kommunicator_db

    kommunicator_db:
        image: postgres:16-alpine
        restart: always
        env_file:
            - .env
        ports:
            - '5432:5432'
        networks:
            - docker_network
        volumes:
            - kommunicator_db:/var/lib/postgresql/data

volumes:
    db:
        driver: local

networks:
    docker_network:
        name: pich_ovh
