version: "3.8"

services:
    server:
        build: .
        ports:
            - "8080:8080"
        networks:
            - docker_network
#        depends_on:
#            - db
#        environment:
#            spring.datasource.url: "jdbc:postgresql://db:5432/kommunicator"

#    db:
#        image: postgres:15.1-alpine
#        restart: always
#        environment:
#            - POSTGRES_USER=postgres
#            - POSTGRES_PASSWORD=postgres
#            - POSTGRES_DB=kommunicator
#        ports:
#            - '5002:5432'
#        networks:
#            - docker_network
#        volumes:
#            - db:/var/lib/postgresql/data

#volumes:
#    db:
#        driver: local

networks:
    docker_network:
        name: pich_ovh
