name: Deploy to pich.ovh

on:
    push:
        branches: [ master ]

jobs:
    deploy:
        runs-on: ubuntu-latest
        environment: pich.ovh
        steps:
            - uses: actions/checkout@v4
            - name: Create .env file
              uses: SpicyPizza/create-envfile@v2
              with:
                envkey_DEVELOPMENT: false
                envkey_POSTGRES_HOST: "kommunicator_db"
                envkey_POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
                envkey_POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
                envkey_POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
                envkey_JWT_SECRET: ${{ secrets.JWT_SECRET }}
                envkey_GOOGLE_APPLICATION_CREDENTIALS: "kommunicator-gac.json"
            - name: Create GAC file
              uses: timheuer/base64-to-file@v1
              with:
                  fileName: "kommunicator-gac.json"
                  fileDir: "./"
                  encodedString: ${{ secrets.GAC_CONTENT }}
            - uses: alex-ac/github-action-ssh-docker-compose@master
              name: Docker-Compose Remote Deployment
              with:
                  ssh_host: ${{ secrets.ORACLE_CLOUD_SSH_HOST }}
                  ssh_private_key: ${{ secrets.ORACLE_CLOUD_SSH_PRIVATE_KEY }}
                  ssh_user: ${{ secrets.ORACLE_CLOUD_SSH_USER }}
                  docker_compose_prefix: kommunicator
